title: TechExcel Win the Database platform
description: In this course, participants will learn to.
theme: just-the-docs

aux_links:
  "Win the Database platform":
    - "https://github.com/microsoft/TechExcel-Win-the-Database-Platform"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note 
    color: purple
  warning:
    title: Warning
    color: red
